export const medicationTypeList = [
  { name: 'Ampoule' },
  { name: 'Capsule' },
  { name: 'Cream' },
  { name: 'Drops' },
  { name: 'Foam' },
  { name: 'Gel' },
  { name: 'Herbs' },
  { name: 'Inhaler' },
  { name: 'Injection' },
  { name: 'Liquid' },
  { name: 'Lotion' },
  { name: 'Lozenge' },
  { name: 'Mouth Wash' },
  { name: 'Oil' },
  { name: 'Ointment' },
  { name: 'Paste' },
  { name: 'Pills' },
  { name: 'Powder' },
  { name: 'Resin' },
  { name: 'Sachet' },
  { name: 'Skin patch' },
  { name: 'Solution' },
  { name: 'Spray' },
  { name: 'Suppository' },
  { name: 'Suspenders/Suspension' },
  { name: 'Syrup' },
  { name: 'Tablet' },
];

export const dosageList = [
  { name: 'Applicatorfuls' },
  { name: 'Bags' },
  { name: 'Bars' },
  { name: 'Capsules' },
  { name: 'Doses' },
  { name: 'Dropperfuls' },
  { name: 'Drops' },
  { name: 'Grams (g)' },
  { name: 'Inhalations' },
  { name: 'Lozenges' },
  { name: 'Micrograms (mcg)' },
  { name: 'Milligrams (mg)' },
  { name: 'Milliliters (ml)' },
  { name: 'Packets' },
  { name: 'Pads' },
  { name: 'Patches' },
  { name: 'Percent (%)' },
  { name: 'Puffs' },
  { name: 'Scoops' },
  { name: 'Shots' },
  { name: 'Sprays' },
  { name: 'Suppositories' },
  { name: 'Syringe' },
  { name: 'Tablespoons (tbsp)' },
  { name: 'Tablets' },
  { name: 'Teaspoons (tsp)' },
  { name: 'Units (U)' },
];

export const frequencyList = [
  { name: 'At Bedtime' },
  { name: 'Daily' },
  { name: 'Every Morning' },
  { name: 'Every Other Day' },
  { name: 'Before Meal' },
  { name: 'After Meal' },
  { name: '2 Times a Day' },
  { name: '3 Times a Day' },
  { name: '4 Times a Day' },
  { name: 'Hourly' },
  { name: 'Every 2 Hours' },
  { name: 'Every 4 Hours' },
  { name: 'Every 6 Hours' },
  { name: 'Every 8 Hours' },
  { name: 'Every 10 Hours' },
  { name: 'Every 12 Hours' },
  { name: 'Weekly' },
  { name: 'Every 2 Weeks' },
  { name: 'Every 3 Weeks' },
  { name: 'Every 4 Weeks' },
  { name: 'Every 5 Weeks' },
  { name: 'Every 6 Weeks' },
  { name: 'Monthly' },
  { name: '2 Times a Month' },
  { name: '3 Times a Month' },
  { name: 'Yearly' },
  { name: '2 Times a Year' },
  { name: '3 Times a Year' },
  { name: '4 Times a Year' },
  { name: '5 Times a Year' },
  { name: '6 Times a Year' },
  { name: '7 Times a Year' },
  { name: '8 Times a Year' },
  { name: '9 Times a Year' },
  { name: '10 Times a Year' },
  { name: '11 Times a Year' },
];
